# docker buildx build -t "verlai/verl:ngc-th2.4.0-v0.0.1" -f docker/Dockerfile.th2.4.0 .

FROM verlai/verl:ngc-base-v0.0.1

RUN pip3 install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124
