# docker buildx build -t "haibinlin/verl:th2.4.0-cu121-vllm0.5.4" -f docker/Dockerfile.th2.4.0 .

FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

LABEL com.nvidia.volumes.needed="nvidia_driver"
LABEL com.nvidia.cuda.version=
ENV NVIDIA_VISIBLE_DEVICES= \
    NVIDIA_REQUIRE_CUDA="cuda>=11.0" \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64

RUN apt-get -o Acquire::ForceIPv4=true update && apt-get install git vim -y

RUN apt install python3 python3-pip -y

RUN pip3 install --no-cache-dir -U pip 'setuptools==69.5.1' wheel packaging --upgrade

# install OpenMPI
RUN apt-get install -yq --no-install-recommends \
        cmake \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        openssh-server \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# configure OpenSSH
RUN mkdir -p /var/run/sshd && \
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Install latest open source torch
RUN python3 -m pip install --no-cache-dir numpy
RUN pip3 install --no-cache-dir torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 \
    --index-url https://download.pytorch.org/whl/cu121

# install common libs
RUN pip3 install --no-cache-dir -U \
    accelerate \
    codetiming \
    dill \
    hydra-core \
    numpy \
    pybind11 \
    tensordict \
    transformers \
    flash-attn --no-build-isolation \
    vllm==0.6.3

# intall apex
WORKDIR /tmp/third_party

# install apex
# check their github repo for the latest installation command. the command changes from time to time.
RUN MAX_JOBS=4 pip3 install -v --disable-pip-version-check --no-cache-dir --no-build-isolation \
    --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" \
    git+https://github.com/NVIDIA/apex

