# docker buildx build -t "haibinlin/verl:th2.4.0-cu121-vllm0.5.4" -f docker/Dockerfile.th2.4.0 .

FROM nvcr.io/nvidia/pytorch:24.05-py3

# uninstall nv-pytorch fork
RUN pip3 uninstall pytorch-quantization \
     pytorch-triton \
     torch \
     torch-tensorrt \
     torchvision \
     xgboost transformer_engine flash_attn \
     apex megatron-core -y
