name: cpu_unit_tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - v0.*
  pull_request:
    branches:
      - main
      - v0.*
    paths:
      - "**/*.py"
      - .github/workflows/cpu_unit_tests.yml
      - "!recipe/**/*.py"

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare permissions just read content.
permissions:
  contents: read

jobs:
  cpu_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Increase this timeout value as needed
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the current repository
        run: |
          pip install -e .[test,prime]
          pip install --upgrade "ray>=2.40.0"
      - name: Running data proto test
        run: |
          cd tests
          pytest -s -x test_protocol.py
      - name: running utils cpu tests
        run: |
          cd tests/utils/cpu_tests
          pytest -s -x .
      - name: Running trainer tests
        run: |
          cd tests/trainer
          pytest -s -x .
      - name: Running worker tests
        run: |
          cd tests/workers/reward_manager
          pytest -s -x .
      - name: Running dataset tests
        run: |
          [ ! -d "$HOME/verl-data" ] && git clone --depth 1 https://github.com/eric-haibin-lin/verl-data ~/verl-data
          python3 examples/data_preprocess/geo3k.py
          pytest -s -x tests/utils/gpu_tests/dataset/test_rl_dataset.py
          pytest -s -x tests/utils/gpu_tests/dataset/test_sft_dataset.py
      - name: Running ray tests that can be tested on CPU machines
          cd tests/single_controller
          pytest -s -x --ignore=test_check_worker_alive_on_cpu.py -k with_cpu .
      - name: Running sandbox tests
        run: |
          cd tests/utils/reward_score
          pytest -s -x .